config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    post 'follow/:id', to: 'friends#follow', as: 'follow_user'
    delete 'follow/:id', to: 'friends#unfollow', as: 'unfollow_user'
    
  end 

  resources :tweets do 
    post 'retweet', to: "tweets#retweet"
    
    member do
      put "like", to: "tweets#upvote"
      put "dislike", to: "tweets#downvote"
    end
  end

  resources :friends do 
    get 'tweets_for_me/:id', to:'friends#show'
  end
  



  

  
  get 'users/show', to: 'users#show'
  root 'tweets#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  accepts_nested_attributes_for :user
  has_many  :likes, dependent: :destroy
  validates :content, presence: true
  acts_as_votable
  has_many :retweets ,dependent: :destroy
  
  
  scope :tweets_for_me, -> (user) { Tweet.where(user_id: user.friends.pluck(:friend_id).uniq) }
  
  
  #delegate :profile_photo, to: :user, prefix: :true
  
 
  def self.search_my_tweets(x)
    @my_tweets = Tweet.all 
    my_tweet_id_array = [] 
    @my_tweets.each do |my_tweet|  
        if my_tweet.content.include? "#{x}" 
            my_tweet_id_array << my_tweet.id
        end
    end
    self.where(id: my_tweet_id_array)
  end

  def share
    Tweet.where(origin: self.id).count
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy retweets]
  before_action :authenticate_user!, exept: [:index,:show]
  skip_before_action :verify_authenticity_token, :only => [:index, :show,:new ]
  # GET /tweets or /tweets.json

 

  def upvote 
    @tweet = Tweet.find(params[:id])
    @tweet.upvote_by current_user
    redirect_to tweets_path
  end  
  
  def downvote
    @tweet = Tweet.find(params[:id])
    @tweet.downvote_by current_user
    redirect_to tweets_path
  end

  def view_Like
    @tweet = Tweet.find(params[:id])
    @tweet.upvote_by current_user
    respond_to do |format|
      # format.html { redirect_to root_url, alert: 'Page not accessible' }
      format.html { redirect_to tweets_likes_path}
      format.json { render :likes, status: :created, location: @tweet }
    end
    
  end  


  def retweet

    if current_user
      @tweet = Tweet.find(params[:tweet_id])
      Tweet.create(content: @tweet.content , user_id: current_user.id, origin: @tweet.id)
    end
    redirect_to root_path
  end


  def index
    @q = Tweet.ransack(params[:q])

    
    if params[:tweetsearch].present?
      @tweets = Tweet.search_my_tweets(params[:tweetsearch]).page(params[:page]).order("created_at DESC")
    elsif params[:hashtag].present?
      @tweets = Tweet.search_my_tweets("##{params[:hashtag]}").page(params[:page]).order("created_at DESC")
    end

    if user_signed_in?
      @tweet = current_user.tweets.build
      @tweets =@q.result(distinct: true).tweets_for_me(current_user).paginate(page: params[:page], per_page: 5)
      #@tweets = Tweet.paginate(page: params[:page], per_page: 5)
     
      @likes = Like.all
      @retweet = Retweet.all
      @tweet = Tweet.new
    else
      @tweets=(@q.result(distinct: true)).all
    end
    return @tweets, @tweet

  end


  # GET /tweets/1 or /tweets/1.json
  def show
    @users = []
    @tweet = Tweet.find(params[:id])
    @tweet.likes.each do |like|
      @users.push(User.find(like.user_id))
    end
    return @tweet, @users
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
    @users = User.pluck :profile_photo, :id, :username, :profile_photo
    
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params.merge(user: current_user))
    @tweet.user_id = current_user.id
    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    if @tweet.user.id == current_user.id
      respond_to do |format|
        if @tweet.update(tweet_params)
          format.html { redirect_to @tweet, notice: "Tweet was successfully updated." }
          format.json { render :show, status: :ok, location: @tweet }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @tweet.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to tweets_path, notice: 'Only admins or the user who created the story can update'
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end
    

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:content, :retweet ,:origin, user_attributes: [:username , :profile_photo])
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local:true) do |form| %>
    
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field mb-3 text-11">
      <%= form.text_area :content , placeholder: 'Your next Tweet', required: true, maxlength:"140", class: " text-11 form-control rounded-pill rounded ml-4", style: "width:90%; resize:none;" %>
  </div>

  <div class="actions">
    <%= form.submit "New Tweet", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<div class="row">
  <div class="col-md-2">
    <% if current_user %>
      <h2 class="text-primary">
        <%=  "Bienvenid@" %> <%=current_user.username%>
      </h2>  
    <% end %>
  </div>
</div>

<% if user_signed_in? %>
  <div class="col-12 border border-secondary rounded">
    <article class="media p-2">
      <div class="align-self-start">
  
        <img src="<%= current_user.profile_photo %>" width="60" height="60" class="round-circle mb-2" >
      
      </div>
      <div class="media-body">
        <div class=" container mt-0">
          <%= render 'form', tweet: @tweet %>
        </div>
      </div>
    </article>
  </div>
<% end %>


    

 <%= link_to 'add new friends', users_show_path, class: "btn btn-info btn-sm my-2" %>

<br>
<h2>Tweets</h2>

<div class = "container d-flex justify-content-left">
  <div class="col-md-3 offset-md-2">
     <%= search_form_for @q do |f| %>
          <div class="form-group">
            <%= f.label :content_cont, 'Tweet Content', class: 'h4 font-weight-bold'  %>
            <%= f.search_field :content_cont, class: 'form-control', placeholder: 'Search Content' %>
          </div>
          <%= f.submit 'Search', class: 'btn btn-info' %>
        <% end %>
  </div>
</div>




<% @tweets.each do |tweet| %>


  <div class="card mx-auto col-md-6 mb-3" style="max-width: 650px;">
    <div class="row no-gutters">
      <div class="col-md-2 py-4"> 
        <img src="<%= tweet.user&.profile_photo %>"width="80" height="80" class="rounded-circle mb-2 mx-4" >  
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-user pr-8"><%= tweet.user %> .
          <small class="text-muted display-12"><%= link_to time_ago_in_words(tweet.created_at),tweet %></small>
          </h5>
          

          <p>
            <% content_tweet_array = tweet.content.split%>
            <% content_tweet_array.each do |element|%>
              <% if element.start_with?("#") %>
                  <% element.slice!(0) %>
                  <a href="?hashtag=<%= element %>">#<%= element %></a>
              <% else %>
              <%= element %>
              <% end %>
            <% end %>  
          </p>  

        </div>
        </div>
        <% if user_signed_in? %>
          <div class="col-md-2">
              <button type="button" class=" text-center my-2  btn btn-info"><%= link_to 'Show', tweet %></button>
            <% if current_user.id == tweet.user_id %>
              <button type="button" class="text-center  my-2 btn btn-warning"><%= link_to 'Edit', edit_tweet_path(tweet) %></button>
              <button type="button" class=" text-center my-2 btn btn-danger"><%= link_to 'destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></button>
            <% end %>
          </div>
        <%end%>
        <div class="row">
          <div class="col-md-2">
              <small class="text-muted"><i class="fas fa-thumbs-up fa-x"></i><%= tweet.get_upvotes.size %></small>
          </div>

          <div class="col-md-2">
            <small class="text-muted"><i class="fas fa-thumbs-down fa-x"></i><%= tweet.get_downvotes.size %></small>
          </div>

          <div class="col-md-2">
            <small class="text-muted"><i class="fas fa-retweet"></i><%= tweet.share %></small>
          </div>

        </div>
      </div>
    </div>
  <div>
<% end %>




<br>
<div class="row">
  <div class="col-md-8 offset-md-4">
    <%= will_paginate @tweets, :previous_label => ' ', :next_label => ' --> view more tweets' %>
  </div>
</div>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>


<br>
<div class= container>
  <p>
    <strong>origin:</strong>
    <% if @tweet.user_id  !=  @tweet.origin %>
      <%= @tweet.user %>
    <% else %>
        "Propio" 
    <% end %>
  </p>

  <p>
    <strong>Photo:</strong>
    <img src="<%= @tweet.user.profile_photo %>"width="60" height="60" class="rounded-circle mb-2">
  </p>

  <p>
    <strong>Name:</strong>
    <%= @tweet.user %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= @tweet.content %>
  </p>

  <div class= container>
    <%= link_to like_tweet_path(@tweet), method: :put do %>
      <i class="fas fa-thumbs-up fa-x"></i>
      <%= @tweet.get_upvotes.size %>
    <% end %>
    <%= link_to dislike_tweet_path(@tweet), method: :put do %>
      <i class="fas fa-thumbs-down fa-x"></i>
      <%= @tweet.get_downvotes.size %>
    <% end %>
    <%= link_to   tweet_retweet_path(@tweet), method: :post do  %>
      <i class="fas fa-retweet"></i>
      <%= @tweet.share%>
    <% end %>
  </div>

  <div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Like Details
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
      <button class="dropdown-item" type="button">
        <% @tweet.get_upvotes.voters.each do |voter| %>
          <%= voter.username %>  
        <% end%>    
      </button>
    </div>
  </div>

  <div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      DisLike Details
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
      <button class="dropdown-item" type="button">
        <% @tweet.get_downvotes.voters.each do |voter| %>
          <%= voter.username %>  
        <% end%>    
      </button>
    </div>
  </div>
  <br>
  <%= link_to 'Edit', edit_tweet_path(@tweet) %> |
  <%= link_to 'Back', tweets_path %>
  
  
  
</div>